export const clientConsts = {
    STORE_CLIENTS: "STORE_CLIENTS",
    REFRESH_CLIENTS: "REFRESH_CLIENTS",
    UPDATE_CLIENT: "UPDATE_CLIENT",
    STORE_CLIENTS_ACTIVE: "STORE_CLIENTS_ACTIVE",
    REFRESH_CLIENTS_ACTIVE: "REFRESH_CLIENTS_ACTIVE",
    UPDATE_CLIENT_ACTIVE: "UPDATE_CLIENT_ACTIVE",
    STORE_CLIENTS_COMPLETED: "STORE_CLIENTS_COMPLETED",
    REFRESH_CLIENTS_COMPLETED: "REFRESH_CLIENTS_COMPLETED",
    UPDATE_CLIENT_COMPLETED: "UPDATE_CLIENT_COMPLETED",
    UPDATE_CLIENT_ALL: "UPDATE_CLIENT_ALL"
}